name: main
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - multiqc
  - nextflow
  - bbmap
  - megahit
  - mmseqs2
  - entrez-direct
  - bowtie2
  - samtools
  - spades
  - kraken2
  - rsync
  - motus=3.1.0
  - bcftools
  # - humann
  # - metaphlan