name: main
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - fastqc
  - multiqc
  - bbmap
  - megahit
  - entrez-direct
  - bowtie2
  - samtools
  - rsync
  - pysam
  - biopython
  - motus=3.1.0
  # - bcftools
  # - mmseqs2
  # - spades
  # - kraken2
  # - humann
  # - metaphlan